### ISSUE TITLE
New development design patterns seem to have wrong GO term

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#102]
In the abnormalDevelopmentOfAnatomicalEntity.yaml the general 'biological process' term (GO:0008150) seems to have been used rather than the 'developmental process' term (GO:0032502).

See #94 for original request.

**Comment by malcolmfisher103** [comment]
I identified this issue as Josh re-ran his mapping scripts on our legacy data and most of the development related GO based terms were mapped to 'XPO:0133403:abnormal developmental process'.

**Comment by seger** [comment]
Good catch. I've opened a ticket on uPheno. @matentzn
