### ISSUE TITLE
Some missing 'abnormal morphology' terms for new XAO terms.

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#105]
In the latest release some XAO terms, including XAO:0005321(intercanthal region) and XAO:0005320(roof of mouth), do not have appropriate 'abnormal morphology [XAO]' format XPO terms. I don't think these hits any of our rules for blacklisting a term, do they need to be specifically whitelisted? If so will this be an ongoing issue as new XAO terms are added? The new XAO's are represented in several other XPO template forms including 'abnormally necrotic' and 'abnormal development of' so perhaps there is some difference in the way 'abnormal morphology' is processed that has caused this.

**Comment by malcolmfisher103** [comment]
This seems to affect terms between XAO:0005283 and XAO:0005321, though I haven't checked exhaustively.

**Comment by matentzn** [comment]
@seger abnormal morphology is [not configured in the automated XAO pipeline](https://github.com/obophenotype/xenopus-phenotype-ontology/blob/master/src/patterns/pattern-config.yaml). @malcolmfisher103 this would explain your issue; abnormal morphology terms are not created automatically!

**Comment by seger** [comment]
@matentzn @malcolmfisher103  OK, I will add it to the specification.
