### ISSUE TITLE
Obsoletion of XPO:0100068 ! abnormal anatomical region has created several 'orphan' terms.

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#110]
The obsoletion of XPO:0100068 (abnormal anatomical region) has left several terms without a path to XPO:00000000 (Xenopus Phenotype).  Perhaps rather than being obsoleted this needs to be part of something equivalent to the Gene Ontology's 'gocheck_do_not_manually_annotate' subset of terms which are required structurally in the ontology but are not themselves appropriate for use in annotation. 

See below for the orphaned anatomical region branches.
![image](https://user-images.githubusercontent.com/23216004/74685003-45bcc000-519b-11ea-8608-63f1e46c0c9b.png)

**Comment by matentzn** [comment]
Which file are you using?

https://www.ebi.ac.uk/ols/ontologies/xpo

Does not seem to share this problem (i.e. there are no orphaned classes). Are you using http://purl.obolibrary.org/obo/xpo.owl and http://purl.obolibrary.org/obo/xpo.obo seem fine to me!

**Comment by matentzn** [comment]
But in general I agree, these high level grouping classes should be kept to give some structure; @seger we could create a "do not annotate" template (a table like the obsolete.tsv one) that generates the "do not annotate" annotation for terms like this one!

**Comment by seger** [comment]
Created new issue #112 to create a "do not annotate" template.
