### ISSUE TITLE
Inconsistent letter case of term labels

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#114]
A few patterns capitalize the term label while most start with lower case, e.g. "Abnormally localised whole organism" but "absent whole organism". Could we make these all consistent, either by fixing the pattern configurations and/or having the release pipeline force all labels to start with lower case?

(Low priority.)

**Comment by matentzn** [comment]
This should fix it:

https://github.com/obophenotype/upheno/commit/343c30973ca1191650d6b3544d26d37dbdde39ef

**Comment by matentzn** [comment]
Thanks for noticing this! I changed it for every ontology!

**Comment by seger** [comment]
Looks great - thanks!
