### ISSUE TITLE
New Pattern request 'Abnormal Morphology Of Anatomical Entity In Location'

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#116]
## Preferred term label

Abnormal Morphology Of Anatomical Entity In Location

## Textual definition

Any abnormality in the shape or constitution of the [Anatomical Entity] in the [Location]. 

## Suggested parent terms

abnormal morphology of [Anatomical Entity]
abnormal morphology of [Location]

We would expect this to subsume what are currently somewhat orphaned temp terms such as many of the '[XAO] in regenerating hindlimb/forelimb' terms.

What follows is a partial list drawn from our review of the existing temp terms neding switched entities. I know Erik said he should be able to extract these but I thought I would provide some examples.

Anatomical Entity XAO|Anatomical entity name|Location XAO|Location name|
|----|----|----|----|
|XAO:0003032|digit|XAO:0004107|regenerating hindlimb|
|XAO:0004300|foot|XAO:0004107|regenerating hindlimb|
|XAO:0003211|tarsus|XAO:0004107|regenerating hindlimb|
|XAO:0003213|tibia-fibula|XAO:0004107|regenerating hindlimb|
|XAO:0003214|femur|XAO:0004107|regenerating hindlimb|

**Comment by MardiNenni** [comment]
add to abnormalMorphologyOfAnatomicalEntityInLocation.yaml pattern list

Abnormal morphology of epithelial cell (XAO: 0003249) in foregut endoderm (XAO: 0004513)
