### ISSUE TITLE
Pipeline not creating new terms based on new XAO terms

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#123]
Some new terms have been added in the latest XAO, but the pipeline is failing to create new XPO classes with the patterns that we automatically apply to all non-blacklisted XAO terms (in src/patterns/data/anatomy). The new XAO terms have IDs XAO_0005322 to XAO_0005327. They do appear in the XAO import (e.g. tadpole, XAO_0005322), and it's possible to make new XPO terms with manual patterns (e.g. wholly dorsalized tadpole, XPO_0141408), but there is no “abnormal tadpole” etc.

**Comment by seger** [comment]
The most recent update of the XPO and all of the release files can be found in the new_release branch.

**Comment by matentzn** [comment]
Seems fine now, can you check again? I think it was just that the pipeline was out of sync. Can you point me to your instructions on how you make a release to double check the procedure?

**Comment by matentzn** [comment]
(maybe get used to use `-B` whenever you do a make command like `sh run.sh make prepare_release -B`. This regenerates everything from scratch).

**Comment by seger** [comment]
> Seems fine now, can you check again? I think it was just that the pipeline was out of sync. Can you point me to your instructions on how you make a release to double check the procedure?

@matentzn I use exactly the commands shown in the wiki: https://github.com/obophenotype/xenopus-phenotype-ontology/wiki/Patterns-pre-processing-pipeline. I will try including the -B flag from now on.

**Comment by seger** [comment]
Looks good!
