### ISSUE TITLE
New terms being created from obsolete XAO terms

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#124]
The most recent XAO has two terms that have been obsoleted: XAO_0005276 (obsolete left optic vesicle) and XAO_0005277 (obsolete right optic vesicle). I obsoleted all associated XPO terms – see the last 14 lines in src/patterns/templates/xpo-obsolete.tsv. But the pipeline is now generating new XPO terms from these with labels like “abnormal obsolete left optic vesicle” (see XPO_0141453 and XPO_0141454 and their children).

**Comment by seger** [comment]
The most recent update of the XPO and all of the release files can be found in the new_release branch.

**Comment by matentzn** [comment]
Note that for example your `XPO_0138116` uses `XAO_0005276` in the manual pipeline! This needs to be fixed manually!

![image](https://user-images.githubusercontent.com/7070631/86210148-c691bc80-bb7c-11ea-8964-63d7c5d9eb90.png)

**Comment by matentzn** [comment]
```
~/ws/xenopus-phenotype-ontology/src/ontology new_release $ grep -r "XPO_0138116" ../patterns/data/
../patterns/data//manual/abnormallyDecreasedOccurrenceOfBiologicalProcessInLocation.tsv
```

**Comment by matentzn** [comment]
Otherwise this ticket should be fixed now in the `new_release` branch.. I ran the release pipeline again as well, so check out `xpo.owl` to see how it looks. Once you fix the above, you can run it again!

**Comment by seger** [comment]
I've obsoleted those terms in the manual pipeline. All looks good after running the release pipeline.
