### ISSUE TITLE
Terms with two labels

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#127]
Some terms such as 'mislocalized cement gland' (XPO:0103842) have 2 labels. The additional labels should be made into exact synonyms. The longer 'abnormally localised [XAO]' labels should be the ones synonymized in those cases. Many of the other instances are for obsoleted terms.

We should also apply consistent usage with respect to (mis)localised vs. (mis)localized.

**Comment by matentzn** [comment]
Indeed! We should probably implement a safeguard against this.

| XPO ID | Label1 | Label2 |
| ---- | ---- | ------|
| XPO:0103403 | abnormally increased number of multiciliated cell in the epidermis inner layer | obsolete increased number of multiciliated cell in the epidermis inner layer |
| XPO:0103403 | obsolete increased number of multiciliated cell in the epidermis inner layer | abnormally increased number of multiciliated cell in the epidermis inner layer |
| XPO:0103581 | decreased length of posterior region | obsolete decreased length of posterior region |
| XPO:0103581 | obsolete decreased length of posterior region | decreased length of posterior region |
| XPO:0103651 | abnormally decreased number of multiciliated cell in the epidermis outer layer | obsolete increased number of multiciliated cell in the epidermis outer layer |
| XPO:0103651 | obsolete increased number of multiciliated cell in the epidermis outer layer | abnormally decreased number of multiciliated cell in the epidermis outer layer |
| XPO:0103703 | abnormal bending of dorsal tail | obsolete abnormal bending of dorsal tail |
| XPO:0103703 | obsolete abnormal bending of dorsal tail | abnormal bending of dorsal tail |
| XPO:0103842 | abnormally localised cement gland | mislocalized cement gland |
| XPO:0103842 | mislocalized cement gland | abnormally localised cement gland |
| XPO:0103843 | abnormally localised head | mislocalized head |
| XPO:0103843 | mislocalized head | abnormally localised head |
| XPO:0103844 | abnormally localised neural tube | mislocalized neural tube |
| XPO:0103844 | mislocalized neural tube | abnormally localised neural tube |
| XPO:0103845 | abnormally localised tail | mislocalized tail |
| XPO:0103845 | mislocalized tail | abnormally localised tail |
| XPO:0103846 | abnormally localised utricle | mislocalized utricle |
| XPO:0103846 | mislocalized utricle | abnormally localised utricle |

I think the majority should be fixable by removing them from the `manual` terms. What I usually do is check them like this:

```
~/ws/xenopus-phenotype-ontology/src/patterns/data (master) $ grep -r "XPO_0103842" */*.tsv
anatomy/mislocalisedAnatomicalEntity.tsv:http://purl.obolibrary.org/obo/XPO_0103842	http://purl.obolibrary.org/obo/XAO_0000033
manual/mislocalisedAnatomicalEntity.tsv:http://purl.obolibrary.org/obo/XPO_0103842	mislocalized cement gland	XAO:0000033	cement gland
```

This should also take care of the consistent spelling.

**Comment by matentzn** [comment]
I have made a new pull request to add the additional quality control test. It fails now because of the two labels error and a bunch of trailing whitespace errors:

https://travis-ci.com/github/obophenotype/xenopus-phenotype-ontology/builds/182242385

**Comment by seger** [comment]
Whitespace errors are fixed here: https://github.com/obophenotype/upheno/pull/732

**Comment by matentzn** [comment]
Awesome. merged in now. thank you!
