### ISSUE TITLE
Additional synonyms for abnormallyArrestedBiologicalProcess

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#131]
We would like to request some additional synonyms for the pattern 'abnormallyArrestedBiologicalProcess.yaml'. These should be of the forms - 'incomplete [BiologicalProcess]' and 'failure to complete [BiologicalProcess]'.

**Comment by sbello** [comment]
The MP also has 'failed [BiologicalProcess]' and '[BiologicalProcess] arrest' as synonyms for some of these terms.

**Comment by ybradford** [comment]
I agree with the request to add these synonyms.

**Comment by matentzn** [comment]
@seger do you want to try to do a pull request on 
- http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyArrestedBiologicalProcessInLocation.yaml
- http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyArrestedBiologicalProcess.yaml

To accomodate these? Let me know if you need help!
