### ISSUE TITLE
Replace temporary edematous terms

### ISSUE THREAD

**Issue by MardiNenni** [obophenotype/xenopus-phenotype-ontology#138]
There seem to be two different types of edema terms in the XPO with 'edema in (XAO)' and 'abnormally edematous (XAO)'. The latter being temporary terms. Can we replace temporary 'abnormally edematous (XAO)' terms with 'edema in (XAO)'. A search on OLS yields 7 temporary terms.

Pharyngeal region
dorsal fin
pericardium
regenerating hindlimb
head 
alimentary system
foregut

**Comment by Xenbase2** [comment]
I was looking at edematous Px yesterday and  ‘’edema in whole embryo might also be useful.
-C

From: MardiNenni ***@***.***>
Reply-To: obophenotype/xenopus-phenotype-ontology ***@***.***>
Date: Thursday, April 1, 2021 at 8:37 AM
To: obophenotype/xenopus-phenotype-ontology ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [obophenotype/xenopus-phenotype-ontology] Replace temporary edematous terms (#138)

[△EXTERNAL]


There seem to be two different types of edema terms in the XPO with 'edema in (XAO)' and 'abnormally edematous (XAO)'. The latter being temporary terms. Can we replace temporary 'abnormally edematous (XAO)' terms with 'edema in (XAO)'. A search on OLS yields 7 temporary terms.

Pharyngeal region
dorsal fin
pericardium
regenerating hindlimb
head
alimentary system
foregut

**Comment by MardiNenni** [comment]
@Xenbase2 Edema in embryo is a term in the XPO (XPO:0141331)
