### ISSUE TITLE
body axis phenotypes

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#147]
### Add XPO terms:

- duplicated main body axis
- partially dorso-anteriorized embryo
- partially dorso-anteriorized tadpole
- wholly dorso-anteriorized embryo
- wholly dorso-anteriorized tadpole
- partially ventro-posteriorized embryo
- partially ventro-posteriorized tadpole
- wholly ventro-posteriorized embryo
- wholly ventro-posteriorized tadpole

Deprecate and add 'replace_by' relationship to 'duplicated main body axis':
- duplicated anatomical axis (http://purl.obolibrary.org/obo/XPO_0115823)

Deprecate and add 'consider' relationship to 'duplicated main body axis':
- duplicated anterior-posterior axis (http://purl.obolibrary.org/obo/XPO_0115824)
- duplicated dorsal-ventral axis (http://purl.obolibrary.org/obo/XPO_0115825)

### Require:
New XAO term: 'main body axis'
xenopus-anatomy/xao/issues/57

New PATO terms:

- dorso-anteriorized
  - partially dorso-anteriorized
  - wholly dorso-anteriorized
- ventro-posteriorized
  - partially ventro-posteriorized
  - wholly ventro-posteriorized

Also fix spelling of current PATO terms:

- anterioralized --> anteriorized
- posterioralized --> posteriorized

**Comment by malcolmfisher103** [comment]
Hi Erik,

That looks good to me. I'm not sure if the 'consider' relationship will let us traverse them in our phenotype results but that is a website/curation side issue. It may be that we can just do a wholesale replace operation within the database to update the existing axis duplication terms.

**Comment by seger** [comment]
This is waiting on the merging of the needed terms into PATO.
