### ISSUE TITLE
Cilium motility phenotypes refer to an obsolete GO class

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#154]
The phenotypes based on these patterns...

abnormalAbsenceOfMotilityOfCellularComponentInLocation
abnormallyDecreasedMotilityOfCellularComponentInLocation
abnormallyIncreasedMotilityOfCellularComponentInLocation
abnormalMotilityOfCellularComponent

...refer to the obsolete GO class GO:0006928 'movement of cell or subcellular component'.

See https://github.com/obophenotype/xenopus-phenotype-ontology/pull/152

**Comment by matentzn** [comment]
Can you describe how you propose to solve this issue? I will make sure some uPheno cilium experts will take a look and comment on your solution.

**Comment by seger** [comment]
@matentzn Reading through the original GO ticket and searching open issues, I'm not entirely following what the replacement(s) for 'movement of cell or subcellular component' would be. There is a comment there about splitting these "for the BP refactoring" but lacking any other references:

https://github.com/geneontology/go-ontology/issues/19809#issuecomment-1077889411

Perhaps the fastest solution for us would be to make a new set of patterns that would be a bit more specific than the current ones listed in my original comment, but still appropriate for the cilium motility phenotypes? We use that current set only for cilia.

Could we make, e.g., abnormalMicrotubuleBasedMovementOfCellularComponent, which would be similarly structured as abnormalMotilityOfCellularComponent?

```
classes:
  process quality: PATO:0001236
  abnormal: PATO:0000460
  cellular component: GO:0005575
  microtubule-based movement: GO:0007018  [this is the GO parent of GO:0003341 cilium movement]

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  results_in_movement_of: RO:0002565
```

**Comment by matentzn** [comment]
I am not the right person for answering this question, but I have reached out to @rays22 and others to help out :) Ping me again if you don't get a response soon!

**Comment by sbello** [comment]
I think @seger is correct we need to obsolete these patterns. Do we need to have motility specific patterns or would these fit in the general biological process pattern (http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalBiologicalProcess.yaml)? I'm inclined to think these could just fit in the general biological process

We do need to add abnormal biological process in location. We already have the decreased/increased child patterns.

**Comment by matentzn** [comment]
@pfey03, you are close to GO, do you have an opinion here?

**Comment by pfey03** [comment]
@sbello We have abnormal biological process in location: https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/abnormalBiologicalProcessInLocation.yaml

**Comment by pfey03** [comment]
Also, since I did not use the above patterns, maybe they need to be more defined unless some need it broader.Patterns should not be so specific that they are dependent on GO terms in my opinion. 

GO obsoletes all single steo processes, the morphing list is here: 
[https://docs.google.com/spreadsheets/d/1x69ACAZmGJA7vK_UKJp5aFrF41AvHeSL7deSwc3rex0/edit#gid=0](https://docs.google.com/spreadsheets/d/1x69ACAZmGJA7vK_UKJp5aFrF41AvHeSL7deSwc3rex0/edit#gid=0)

I have to change quite some phenotypes  and then patterns, we have some in the 'protein phosphorylation' branch; in GO I have already updated all, I will work again with phenotypes after the GO meeting in October.

**Comment by seger** [comment]
@sbello I wouldn't have any objection to using the abnormalBiologicalProcess[InLocation] patterns with GO:0003341 'cilium movement' (synonym 'ciliary motility').

**Comment by pfey03** [comment]
Ye, that makes sense

**Comment by sbello** [comment]
@pfey03 Yep, missed that pattern. Doesn't seem like we need these then. I did put this on the agenda for tomorrow's call but it may be quick or possibly we don't need to discuss this at all.
