### ISSUE TITLE
XPO is using LFS - which has been squashed by github for our organisation

### ISSUE THREAD

**Issue by matentzn** [obophenotype/xenopus-phenotype-ontology#155]
The `obophenotype` organisation received a strange email informing us that due to our excessive usage of LFS 150% over the limit, LFS support is shut down. Looking at the settings, it seems that XPO is the only users of LFS:

![image](https://user-images.githubusercontent.com/7070631/187617150-b1cb4072-a55c-40d9-9e37-f173ad5b9fd4.png)

You should know now LFS does not work anymore and it would be best if you stopped using it so the ban of our org from the service is suspended (makes it easier to make future experiments).

@seger do you know why and how XPO uses LFS?

**Comment by cmungall** [comment]
If there is a need for big files we can explore other ways like S3 but even for larger ontologies the methodology of simply including the files with the releases suffices

**Comment by seger** [comment]
@matentzn @cmungall Yesterday I was trying to push a branch of the XPO to our repository that now has two files exceeding 100 MB (xpo.owl and xpo-full.owl) and as a test I tried setting up LFS to handle those. I didn't realize it this would cause issues – apologies for that. I actually deleted that branch and was planning to ask around for advice so I would really understand what I was doing (which I should have done in the first place).

**Comment by matentzn** [comment]
@seger, we now deal with this differently - let me know when you are ready to make a release - I will update the repo with the new feature. Essentially, we will remove all xpo files files from the git repo, attach them to the github release instead and redirect the XPO PURLs there. Most ontologies in our spheres are already doing that, see, for example Uberon, Mondo, MP.

**Comment by seger** [comment]
@matentzn The new XPO release is ready to go and everything looks OK. I merged the changes into my main branch locally but have not pushed the changes or published the files anywhere yet. There are two files greater than 100MB, xpo-full.owl and xpo.owl. Let me know how I should proceed. Thanks for your help.

**Comment by matentzn** [comment]
@seger great. This is what should happen:

1. `git rm` all release files (top level dir, xpo.owl, xpo-full.json, etc etc) _aside from xpo-base.owl_ (which is useful for reviewing releases) from your local xpo repo
2. Add all release files to `.gitignore`
3. Run the release again and make a PR (only the xpo-base should have changed)
4. After merging the release PR create a GitHub release as usual. Attach all 9 or so XPO release artefacts to the release "as binaries" (you will see what I mean in the edit release page)
5. Make a PR on the [XPO PURL config](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/xpo.yml). Model it after the one [in Uberon](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/uberon.yml#L9). The important thing here is to switch releases from raw.github to `latest/release`. Tag me on PR and I will review it.

**Comment by seger** [comment]
@matentzn After following the instructions I am still getting an error about the two >100MB files when I try to push the update to GH. Would this be because these large files exist in older commits (from periodically running the release pipeline) even though they are removed from the latest commit?

**Comment by matentzn** [comment]
Yea exactly. You have to delete them from all commits where the size is larger than 100. If you are still on a branch, it may be easier to copy the repo contents somewhere, go back to master, copy the contents back. If you made the bad commit to the master branch you need to google how to delete the files from them.

**Comment by seger** [comment]
@matentzn OK, it wasn't as painful as feared to resolve that. So the new release has been made, correctly I hope!? And there is a PR to update the XPO PURL config.
