### ISSUE TITLE
Please attached xpo-base (all files) to release

### ISSUE THREAD

**Issue by matentzn** [obophenotype/xenopus-phenotype-ontology#156]
It is ok to leave the base files checked git in as a way to review the release, but i usually recommend something slightly different:

- [x] Only check in `xpo-base.owl`, and `xpo.obo`. These files are great for reviewing that everything went ok with the release.
- [x] Attach _all_ release files to the release (including the above). Right now they are not recognised by the PURL http://purl.obolibrary.org/obo/xpo/xpo-base.owl, because you changed the redirect of the fall-through purl config to the release!
- [x] I recommend to delete xpo-merged.owl and obo as they seem to not be updated anymore.

**Comment by seger** [comment]
xpo-merged.owl and obo have been deleted.
