### ISSUE TITLE
Share table of annotations and map to XPO

### ISSUE THREAD

**Issue by matentzn** [obophenotype/xenopus-phenotype-ontology#20]
@malcolmfisher103 will share the table of all annotations of the past year, and nico will import them and map them to XPO.

@seger The advantage is that @malcolmfisher103 and Christina can start curating against XPO, even if the hierarchy is not yet very uPheno conformant.

Was great meeting you guys!

**Comment by malcolmfisher103** [comment]
I have shared the Google sheet 'Xenbase phenotype annotations for XPO 4-10-2019' with you both.
