### ISSUE TITLE
Review current XPO with XenBase

### ISSUE THREAD

**Issue by matentzn** [obophenotype/xenopus-phenotype-ontology#25]
@malcolmfisher103
@seger 

we should set up a meeting soon to discuss next steps!

**Comment by malcolmfisher103** [comment]
Hi Nico,

Sorry not to get back to you on this sooner. We haven't had a good chance to go over the new release yet, though we are starting now, but we should absolutely have a meeting to discuss things. Erik got in touch about organizing a Skype next week, I don't know how your schedule fits in with a US afternoon meeting.

**Comment by matentzn** [comment]
Hey Malcom! 

Great to hear from you! :) @seger  and I just sat together to help you develop a review scheme for the XPO, which he will forward to you! 

[Here is a table](https://docs.google.com/spreadsheets/d/1mgH7wK5qwkxTK4YOgPEYderEGCp2fkoXLsZtpKyi3Fs/edit?usp=sharing) of all the current XPO terms including their definitions, which should make it easier to review the terminological aspects of XPO!

**Comment by matentzn** [comment]
I would love to meet, but it has to be during an XPO meeting slot; the next one I believe would be next Wednesday? @seger , maybe you want to invite @malcolmfisher103 to the next XPO meeting to get their input?

**Comment by malcolmfisher103** [comment]
Hi Nico/Erik,

Is there an OBO or OWL that reflects the terms in that table and has some of the ontology structure? The current OBOs and OWLs (https://github.com/obophenotype/xenopus-phenotype-ontology/blob/master/xpo.owl) seem quite different with ~500 additional terms.

**Comment by matentzn** [comment]
Yeah we did not run a new release in between. Give me 10-15 min.

**Comment by matentzn** [comment]
Sorry, it took a bit longer. Now its there:

https://raw.githubusercontent.com/obophenotype/xenopus-phenotype-ontology/master/xpo.owl

Open with Protege!

**Comment by malcolmfisher103** [comment]
Thanks Nico, there still seem to be many more terms in the OWL than in the term table you sent us. For instance XPO:0115523 ('abnormal(ly) immature of head (T)') is in the new OWL and OBO files but not in the term table.

Are some terms being excluded for a reason or is there an issue with the SPARQL query?

**Comment by matentzn** [comment]
Yeah must be. I have an incline what it is; I will fix it first thing tomorrow morning so you will have it when you wake up. It actually alerted me to a possible problem with one of the patterns, so the mistake is not for nothing. My suspicion is that one of the patterns we use, by accident, has not synonym or god forbid definition provided with it! Thanks for pointing it out and sorry for the inconvenience. The ontology is definitely up to date, and I think the csv is too, just incomplete.

**Comment by matentzn** [comment]
THANK YOU! Looking forward to more strict feedback!

**Comment by matentzn** [comment]
Will close this in favour of more specialised tickets.
