### ISSUE TITLE
Including GO Development terms

### ISSUE THREAD

**Issue by JoshuaFortriede** [obophenotype/xenopus-phenotype-ontology#26]
The XPO is currently missing a lot of GO based Development terms. 

For instance, the GO term "hindgut development" [GO:0061525] could be the basis for "abnormal hindgut development", and connected to the hindgut portion of the XPO. 

In regards to how these development terms are used, it would be helpful to follow the "develops from" relationships in the XAO.  For instance, hindgut develops from hindgut primordium.  This means that any morphological or developmental terms for hindgut primordium "is_a" abnormal hindgut development. However this "develops_from" graph path can only go so far.  For instance, the central endoderm develops into the foregut endoderm, hindgut primordium, and midgut primordium. So, saying that there was an abnormal central endoderm morphology does not guarantee that there is an abnormal hindgut development, as the morphological abnormality in the central endoderm could be isolated to a region that isn't fated to be hindgut. 

GO also has morphogenesis terms, however I do not believe we would use them much.  I believe we would use the higher level morphology term.  

Notes:

- Abnormal morphology and abnormal development are disjoint from each other.  For instance, an abnormal development could include developmental delay, but the morphology is correct.

**Comment by malcolmfisher103** [comment]
I have created a table of developmental terms we would like to see incorporated initially. This is based off 2 criteria for selecting the relevant XAO terms, either they are in the subset that Erik has previously identified as frequently used in curation or they are terms that have the 'is_a' relationship with some sort of organ class (principally compound organ and its children - cavitated compound organ and solid compound organ).

Where possible I tried to find GO terms linked through UBERON equivalents to the XAO terms, but these did not always exist. 

In the case of the tail/tail bud I couldn't find a development term, only morphogenesis. As Josh has said above these are distinct concepts so 'post-anal tail morphogensis' probably shouldn't be in this table and we should be lobbying GO to add a proper development term.

If possible having XPO terms covering the GO term ancestors for the chosen terms would also be nice to have to provide at least a slightly deeper branching and appropriate higher system level development terms for later slimming. 

We had originally planned to pull terms out based on UBERON class usage, but there were fewer GO terms using UBERON terms than we expected in the main go.owl. There is a more detailed go-plus.owl, but I'm not sure how to extract terms based on the intersection/equivalent class relationships there that incorporate UBERON terms.

The table is at -
https://docs.google.com/spreadsheets/d/1oF1TUPl2HpN7_mzlHy9p9Y2TVnoG1q3WkTA7GzHqqD0/edit?usp=sharing

**Comment by matentzn** [comment]
@malcolmfisher103 

Do not worry too much about existing GO term - UBERON connections. using the various abnormalSomethingInLocation patterns we can make these connections ourselves. Also, if the location is important, shouldnt we map those development terms (if they have a location component) to XAO terms?

@seger, can you break down this ticket here into smaller bits that we can address? First step I think is to decide which of malcoms development terms need a location, and move these to the abnormalBiologicalProcessInLocation pattern. The ones that do not (the location is whole organism), can stay where they are, and we will add them on Wednesday to the abnormalBiologicalProcess.yaml pattern. 

@JoshuaFortriede 

> This means that any morphological or developmental terms for hindgut primordium "is_a" abnormal hindgut development. However this "develops_from" graph path can only go so far.

I am not sure I understand this, could you give an example or two?

**Comment by matentzn** [comment]
@seger I think we still need to deal with this?

**Comment by seger** [comment]
The terms from the table have been added to the XPO. Parts of this ticket have been broken out as #79 and #80.
