### ISSUE TITLE
abnormalMorphologyOfAnatomicalEntity labels

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#29]
The label for the auto generated 'abnormal morphology of {tissue}' classes should be changed to read 'abnormal {tissue} morphology' instead.

**Comment by matentzn** [comment]
Unfortunately, it is not possible to overwrite the general mechanism for creating a definition for a pattern. You have essentially three options:

1. You manually overwrite the names for all morphology terms (many)
2. You lobby on uPheno for getting the abnormalMorphology label done ([I made a comment on your behalf](https://github.com/obophenotype/upheno/issues/374)) 
3. You create a new pattern that deals just with the label generation. This is a quite bad option as it requires multiple tables containing the same entities, and a few lines of code in the makefile to handle this exception.

Lets see where we get with 2.

**Comment by matentzn** [comment]
This should be fixed by https://github.com/obophenotype/upheno/issues/374
