### ISSUE TITLE
Grouping class for behavior phenotypes

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#30]
We should create a sublass of Xenopus Phenotype called 'abnormal behavior' that is a grouping class for a couple of orphans that are currently themselves subclasses of Xenopus Phenotype:

http://purl.obolibrary.org/obo/XPO_0103783 - absent hatching behavior
http://purl.obolibrary.org/obo/XPO_0103784 - absent swimming

There will be more behavior classes added to the XPO in the future.

**Comment by matentzn** [comment]
Ok, the way to do it is this:
1. add "abnormalBehavior" pattern to src/patters/dosdp-patterns/external.txt (if its not already there)
1.  create the corresponding TSV
1. In the 'behavior' column, simply add the filler term for 'behavior' (NBO/GO)

Remember to leave the defined class column blanc, as  this will be filled in automatically.

**Comment by matentzn** [comment]
Ah, when you manually create grouping classes, make sure that they are in the TSV in the data/manual directory, NOT anatomy!
