### ISSUE TITLE
Grouping class for biological process phenotypes

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#31]
We should create a sublass of Xenopus Phenotype called 'abnormal biological process' that is a grouping class for some orphans that are currently themselves subclasses of Xenopus Phenotype:

http://purl.obolibrary.org/obo/XPO_0103447
http://purl.obolibrary.org/obo/XPO_0103443
http://purl.obolibrary.org/obo/XPO_0103444
http://purl.obolibrary.org/obo/XPO_0103445
http://purl.obolibrary.org/obo/XPO_0103446
http://purl.obolibrary.org/obo/XPO_0103772
http://purl.obolibrary.org/obo/XPO_0103884
http://purl.obolibrary.org/obo/XPO_0103642

The following are also orphan subclasses of Xenopus Phenotype but they are biological processes that are located in an anatomical location, e.g. 'absent axon regeneration in optic nerve'. Should these not be connected to the relevant part of the XPO, e.g. an abnormality of optic nerve?

http://purl.obolibrary.org/obo/XPO_0116045
http://purl.obolibrary.org/obo/XPO_0116044
http://purl.obolibrary.org/obo/XPO_0115892
http://purl.obolibrary.org/obo/XPO_0103624
http://purl.obolibrary.org/obo/XPO_0103623
http://purl.obolibrary.org/obo/XPO_0103625
http://purl.obolibrary.org/obo/XPO_0103920
http://purl.obolibrary.org/obo/XPO_0103922
http://purl.obolibrary.org/obo/XPO_0103921
http://purl.obolibrary.org/obo/XPO_0103923
http://purl.obolibrary.org/obo/XPO_0103924
http://purl.obolibrary.org/obo/XPO_0103925
http://purl.obolibrary.org/obo/XPO_0103442

**Comment by matentzn** [comment]
For task number one (grouping class):
1. in src/patterns/data/manual/abnormalBiologicalProcess.tsv simply add a row with GO:'biological process' as filler. Leave the defined_class field blank.

Task number two is a bit more difficult to generalise, and wont be solved before the 18th June; These kinds of additional releations are even more important when it comes to development and affected anatomical entities (causal relations). We will try to develop a way to do that community-wide. If you throw it on our agenda, I will explain to you what the general approach to connect these will look like.
