### ISSUE TITLE
Decide which terms should be obsoleted before first official release

### ISSUE THREAD

**Issue by matentzn** [obophenotype/xenopus-phenotype-ontology#34]

**Comment by malcolmfisher103** [comment]
I have a short list of terms I feel should 
be removed [XPO_terms_for_obsoletion.txt](https://github.com/obophenotype/xenopus-phenotype-ontology/files/3288250/XPO_terms_for_obsoletion.txt) .

These are mostly of 3 types, 'decreased number' terms which are essentially identical to existing 'absent' terms, 'abnormal(ly) normal' terms and terms which appear to have a second related entity missing.

There are also a number of fused terms which are missing the second related entity.
[Fused terms.txt](https://github.com/obophenotype/xenopus-phenotype-ontology/files/3288257/Fused.terms.txt). These should either be removed or modified.

**Comment by matentzn** [comment]
Done in for next release
