### ISSUE TITLE
Additional Behavioral terms

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#39]
Erik asked previously for some other behavioral terms that should be included in the behavior class  (#30) besides swimming and hatching. From a review of the literature we identified several types of behavior associated with Xenopus phenotypes. Of these 8 have precise GO terms ...

|ID|Name|
|---|---|
|GO:0071625|vocalization behavior|
|GO:0007619|courtship behavior|
|GO:0048266|behavioral response to pain|
|GO:0042048|olfactory behavior|
|GO:0007638|mechanosensory behavior|
|GO:0007632|visual behavior|
|GO:0007634|optokinetic behavior|
|GO:0035176|social behavior|

We also identified 3 types of behavioral phenotypes that lack a clear GO term equivalent ...

|Name|
|---|
|collision avoidance behavior/ visual avoidance behavior|
|schooling behavior|
|escape behavior|

Can these non GO terms be added as is or is the correct procedure to request additional terms be added to GO and then use those new GO terms as the basis for XPO terms?

All of these that can be added should probably have 'abnormal behavior' and 'abnormal absence of behavior' terms. Sorry I didn't have these ready in time for the last release.

**Comment by matentzn** [comment]
@malcolmfisher103 There are two options here. 
1) You go the long way via GO; if you want to try, feel free!
2) You go for [NBO](https://github.com/obo-behavior/behavior-ontology), which we also use for behavior. The advantage here is that we can create terms quickly ourselves. ([Check here](https://www.ebi.ac.uk/ols/ontologies/nbo)) if interested!

**Comment by malcolmfisher103** [comment]
Thanks for directing us to the NBO, we'll consider that as an a alternative option.

**Comment by Xenbase2** [comment]
request: increased rate [PATO_0000912]/decreased rate[PATO_0000911] abnormal, absent 'surface breathing', ; increased rate/decreased rate/abnormal 'swimming behaviour', abnormal 'resting posture', absent/abnormal/increased rate/decreased rate 'locomotory behavior'. (surface breathing would be an additional request for new term with NBO)

**Comment by Xenbase2** [comment]
abnormal/absent mating behaviour (GO:0007617)

**Comment by malcolmfisher103** [comment]
|ID|Name|
|---|---|
|GO:0007631|Feeding behavior|
|GO:0007626|locomotory behavior|
|NBO:0000358|resting posture|

**Comment by seger** [comment]
Summary of terms that still need to be added/requested.

|Q|E|
|---|---|
abnormal|collision/visual avoidance behavior - NBO request|
abnormal|schooling behavior - NBO request|
abnormal|escape behavior - NBO request|
increased rate/decreased rate/abnormal/absent|surface breathing - NBO request|
increased rate/decreased rate|GO:swimming behavior|
abnormal|NBO:resting posture|
increased rate/decreased rate|GO:locomotory behavior|
increased rate/decreased rate|GO:feeding behavior|

@matentzn We need to set up NBO imports in the XPO.

**Comment by matentzn** [comment]
Done.

**Comment by seger** [comment]
Awesome! I am writing up the new NBO term requests and will submit tickets soon.

**Comment by matentzn** [comment]
Actually: would you feel comfortable to just make pull requests instead?

**Comment by seger** [comment]
Sure! So I just edit src/ontology/nbo-edit.owl, correct?

**Comment by matentzn** [comment]
I send you an email with instructions. Thank you!

**Comment by seger** [comment]
@seger will add subsumptions to GO terms to NBO so that the behaviors classify correctly.
