### ISSUE TITLE
Several standard PATO terms to apply to most XAO terms.

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#48]
We would like to have terms for 

- [x] ‘absent’(PATO:0000462), 
- [x] ‘mislocalized’(PATO:0000628), 
- [x] ‘decreased size’ (PATO:0000587) 
- [x] ‘increased size’ (PATO:0000586) 

for all XAO terms that aren’t 
- [X] ‘anatomical directions’ (XAO:0003185) or its children,  
- [X] ‘anatomical entity in vitro’ (XAO:0003007) or its children, 
- [x] ‘anatomical axis’ (XAO:0005200) or its children, excepting 'anterior-posterior axis' (XAO:0005202), 
- [x] ‘anatomical side’ (XAO:0005205) or its children, 
- [x]  ‘unspecified’ (XAO:0003003). 

- [x] Add 'necrotic [XAO]' (PATO:0000647) terms for the same set above but including 'anterior-posterior axis' (XAO:0005202) in the terms to be excluded and excluding 'anatomical space' (XAO:0003190) and its children.

**Comment by malcolmfisher103** [comment]
Let me know if these need broken up into separate issues.

**Comment by matentzn** [comment]
No, perfect like this. I an on leave until 10 Sept now; I will deal with this issue on the 20th September. If you need it earlier, ping me an email and I will see that I can fiddle it in before that! :) Thanks Malcom.

**Comment by matentzn** [comment]
We will continue to work on the branch for the time being; I did absent and mislocalised; @seger try to do the rest of this ticket, and let me know if there are any problems.

**Comment by malcolmfisher103** [comment]
I slightly modified the wording in the request regarding 'necrotic' terms as it was ambiguous and open to misinterpretation.

**Comment by seger** [comment]
Need to create new necrotic patterns.
