### ISSUE TITLE
Create new edematous terms.

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#64]
Create terms for ‘edematous [XAO]' (PATO:0001450) for the following XAO terms.

|Name|Term ID|
|-- | --|
|Ventral trunk | XAO:0005260|
|Hindlimb | XAO:0003031|
|Forelimb | XAO:0003030|
|Eye | XAO:0000179|
|Brain | XAO:0000010|
|Spinal cord | XAO:0000020|
|Limb bud | XAO:0003161|
|Tail | XAO:0003026|
|Circulatory system | XAO:0001010|
|Coelom | XAO:0004521|
|epidermis | XAO:0000028|

**Comment by MardiNenni** [comment]
Create terms for ‘edematous [XAO]' (PATO:0001450) for the additional XAO terms.

embryo XAO:0000113
