### ISSUE TITLE
Additional neural crest cell migration terms.

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#69]
Add terms for ‘decreased cell migration of branchial crest’, ‘decreased cell migration of hyoid crest’ and  ‘decreased cell migration of mandibular crest’. ‘decreased cell migration of branchial crest’ should have children ‘decreased cell migration of anterior branchial crest’ and ‘decreased cell migration of posterior branchial crest’.

|Term ID|Name|
|---|---|
|XAO:0000026|branchial crest|
|XAO:0000025|hyoid crest|
|XAO:0000024|mandibular crest|
|XAO:0000026|branchial crest|
|XAO:0004187|anterior branchial crest|
|XAO:0004188|posterior branchial crest|

**Comment by MardiNenni** [comment]
Apply PATO:0002302 'decreased process quality' GO:0016477 to all of the above XAO terms. 

Would also like to add the term PATO:0000460 'abnormal' GO:0001755 'neural crest cell migration'
as a parent of all of the above or just a child of biologicalprocess?

**Comment by matentzn** [comment]
We try to avoid the more general decreased process quality terms now in favour of decreased rate or decreased occurrence; unless you want to deliberately keep this open.
