### ISSUE TITLE
Create 'neoplastic' and 'metaplastic' terms.

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#72]
Create ‘neoplastic [XAO]…’ (PATO:0002011) and ‘metaplastic [XAO]’ (PATO:0002101) terms for the direct is_a descendants of the following terms...

|Term ID|Name|
|--|--|
|XAO:0003041|compound organ|
|XAO:0003165|cavitated compound organ|
|XAO:0003164|solid compound organ|

Neoplastic terms should have synonyms as 'tumorous [XAO]'. If new direct children of the above terms are added we would want new XPO terms created using this approach.

**Comment by MardiNenni** [comment]
@seger What is the status of this issue? Will these new terms be added or was another decision made?

**Comment by seger** [comment]
@MardiNenni They have been added to the XPO in the update branch:

https://github.com/obophenotype/xenopus-phenotype-ontology/blob/update/xpo.owl

I'll email you and Malcolm with a list of the term requests that have been completed in this branch to date and decide whether we want to make a new XPO release.
