### ISSUE TITLE
Add increased and decreased apoptosis terms.

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#82]
Add increased and decreased apoptosis terms for the same XAO terms as absent and increased/decreased size (#48)  with some changes, do not make apoptosis terms for anterior-posterior axis, do not make apoptosis terms for anatomical space (XAO:0003190) and its children. These should be the same set of terms as for 'necrotic' in #48.

There is no increased and decreased apoptosis PATO terms. There is an apoptotic term (PATO:0000638) but I'm not sure how that could be incorporated. Alternatively we could use an approach like the MP where increased and decreased apoptosis are GO related terms. The MP term for [increased apoptosis in kidney](http://www.ontobee.org/ontology/MP?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0011368) has the following equivalencies- 
has part some (increased rate[PATO:0000912] and (inheres in part of some (apoptotic process[GO:0006915] and (occurs in some kidney[UBERON:0002113]))) and (has modifier some abnormal)). 

Perhaps Nico or Erik can speak to the most appropriate approach to create such terms.

**Comment by matentzn** [comment]
This is a matter for uPheno community to decide. I will put on agenda.

**Comment by matentzn** [comment]
Thanks Yvonne, this is great!

@seger Do you want to try and create the patterns @ybradford mentions here yourself? 

1. increasedOccurrenceOfBiologicalProcess (adapted from increasedRateOfBiologicalProcess)
1. increasedOccurrenceOfBiologicalProcessInLocation (adapted from increasedRateOfBiologicalProcessInLocation)
1. apoptoticAnatomicalEntity  (adapted from [blisteredAnatomicalEntity](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/blisteredAnatomicalEntity.yaml))
1. apoptoticAnatomicalEntityInLocation (adapted from [blisteredAnatomicalEntityInLocation](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/blisteredAnatomicalEntityInLocation.yaml))

Create them to the best of your knowledge, and make a pull request on upheno for them! Whenever you have problems, ping me.
