### ISSUE TITLE
Illegal equivalences

### ISSUE THREAD

**Issue by matentzn** [obophenotype/xenopus-phenotype-ontology#83]
The current release of XPO still contains equivalent classes.  We need to make sure that there are no equivalent classes prior to curation:

```
XPO_0126883 = XPO_0115427
XPO_0115822 = XPO_0115429
XPO_0115572 = XPO_0115814
XPO_0115355 = XPO_0115813
XPO_0115590 = XPO_0115818
XPO_0125159 = XPO_0115619
XPO_0125390 = XPO_0115665
XPO_0115694 = XPO_0126435
XPO_0115381 = XPO_0131202
XPO_0125064 = XPO_0115403
XPO_0115815 = XPO_0115600
XPO_0115770 = XPO_0129136
XPO_0115401 = XPO_0125494
XPO_0115327 = XPO_0115796
XPO_0115472 = XPO_0128915
XPO_0115477 = XPO_0124996
XPO_0115478 = XPO_0129558
XPO_0115548 = XPO_0115820
XPO_0131269 = XPO_0115616
XPO_0115657 = XPO_0125365
XPO_0129605 = XPO_0115497
XPO_0115305 = XPO_0115817
XPO_0115769 = XPO_0125791
XPO_0115532 = XPO_0115821
XPO_0115328 = XPO_0125113
XPO_0115521 = XPO_0115812
XPO_0115402 = XPO_0130151
XPO_0115367 = XPO_0129522
XPO_0128534 = XPO_0115696
XPO_0126405 = XPO_0115410
XPO_0115449 = XPO_0125812
XPO_0129925 = XPO_0115377
XPO_0115394 = XPO_0125518
XPO_0115642 = XPO_0115802
XPO_0115493 = XPO_0130287
XPO_0115378 = XPO_0128445
XPO_0115819 = XPO_0115680
XPO_0115749 = XPO_0115800
XPO_0115368 = XPO_0125104
XPO_0126684 = XPO_0115406
XPO_0115803 = XPO_0115564
```
You can reproduce this by running:

`sh run.sh robot reason -I http://purl.obolibrary.org/obo/xpo.owl --equivalent-classes-allowed none -o test.owl`

**Comment by seger** [comment]
@matentzn I think these were all fixed in the current release. In each pair, one class was a TEMP term which was obsoleted and replaced by the other (non-TEMP) class, e.g. lines 51 and after in src/patterns/templates/xpo-replaced.tsv

**Comment by matentzn** [comment]
Fixed in https://github.com/obophenotype/xenopus-phenotype-ontology/pull/84

**Comment by matentzn** [comment]
Rember that you need to 1) add stuff to the obsolete.tsv, 2) remove the respective entry from xpoAnatomicalEntityTEMP.tsv in patterns/data/manual
