### ISSUE TITLE
Consider ridding ourselves of BSPO dependency

### ISSUE THREAD

**Issue by matentzn** [obophenotype/xenopus-phenotype-ontology#86]
If you look through XPO, you will see 5 BSPO terms used:

- BSPO_0000000
- BSPO_0000007
- BSPO_0000016
- BSPO_0000085
- BSPO_0000679

Is it worth replacing those with XAO terms or obsoleting them?  

We could configure a new import of BSPO, which adds another layer of complexity to subsequent alignment efforts (not too much, just trying to get a feel here how important they are). I think altogether there are about 10 XPO terms using those? They are all coming from the very original annotation sets.. 

![image](https://user-images.githubusercontent.com/7070631/65168969-8d4ced80-da3d-11e9-82f0-79f9fe71868e.png)

**Comment by malcolmfisher103** [comment]
I think that apart from BSPO_0000679 (Dorsal margin) all of these have existing XAO counterparts. Dorsal margin only seems to have been used once in our legacy curations and that statement is already malformed as it was an EQE statement and the 2nd entity didn't get incorporated into the XPO term (XPO_0115891).
