### ISSUE TITLE
new terms for cell adhesion

### ISSUE THREAD

**Issue by MardiNenni** [obophenotype/xenopus-phenotype-ontology#88]
parent:
abnormal cell adhesion PATO:0000460, GO:0007155
with children:
increased cell adhesion (PATO:0000470, GO:0007155)
decreased cell adhesion (PATO:0000470, GO:0007155)

**Comment by matentzn** [comment]
I think abnormal cell adhesion should just be abnormalBiologicalProcess;
the other two however; what should the increased actually mean? We dont use amount with biological processes; we use increased occurrence (happens more), increased rate (happens more often during a period of time).. What would fit best here?

**Comment by MardiNenni** [comment]
Lets just do abnormal cell adhesion (PATO:0000460, GO:0007155),  with the parent abnormalBiologicalProcess; and lose the increase/decrease.
