### ISSUE TITLE
Odd subsumption

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#89]
Investigate this odd subsumption in xpo.obo. Did we obsolete XPO:0107363 and forgot to remove it from somewhere? Are there any others?

```
name: obsolete increased size of the dorsal region
def: "An increase in the size of the dorsal region." []
synonym: "enlarged dorsal region" EXACT []
is_a: XPO:0107363 ! obsolete abnormal morphology of dorsal region
is_a: XPO:0129571 ! increased size of the anatomical region
is_obsolete: true
```

**Comment by malcolmfisher103** [comment]
There seem to be about 17 unique obsoleted terms this is happening with, mostly related to regions.

is_a: XPO:0102335 ! obsolete abnormal morphology of head region
is_a: XPO:0103366 ! obsolete decreased size of the tail region
is_a: XPO:0107275 ! obsolete abnormal posterior region
is_a: XPO:0107277 ! obsolete abnormal ventral region
is_a: XPO:0107279 ! obsolete abnormal antero-dorsal region
is_a: XPO:0107280 ! obsolete abnormal antero-ventral region
is_a: XPO:0107281 ! obsolete abnormal postero-dorsal region
is_a: XPO:0107337 ! obsolete abnormal ventro-lateral region
is_a: XPO:0107338 ! obsolete abnormal dorso-lateral region
is_a: XPO:0107360 ! obsolete abnormal morphology of basal region
is_a: XPO:0107361 ! obsolete abnormal morphology of anterior region
is_a: XPO:0107362 ! obsolete abnormal morphology of posterior region
is_a: XPO:0107363 ! obsolete abnormal morphology of dorsal region
is_a: XPO:0107365 ! obsolete abnormal morphology of medial region
is_a: XPO:0107366 ! obsolete abnormal morphology of antero-dorsal region
is_a: XPO:0107424 ! obsolete abnormal morphology of ventro-lateral region
is_a: XPO:0115851 ! obsolete abnormal(ly) quality of heart in left atrium (T)

**Comment by seger** [comment]
The 'obsolete abnormal XX' and 'obsolete abnormal morphology of XX' terms need to be added to the anatomy_config blacklist. Also XPO:0107425.

**Comment by seger** [comment]
Several more obsoleted terms in #45 also have the odd subsumptions. Cleaning those up as well.
