### ISSUE TITLE
Add increased and decreased proliferation terms

### ISSUE THREAD

**Issue by MardiNenni** [obophenotype/xenopus-phenotype-ontology#90]
Add increased occurrence (PATO:0002051)  and decreased occurrence (PATO:0002052) cell population proliferation (GO:0008283) for all XAO terms that aren't:

  ‘anatomical directions’ (XAO:0003185) or its children,
  ‘anatomical entity in vitro’ (XAO:0003007) or its children,
  ‘anatomical axis’ (XAO:0005200) or its children, 
  ‘anatomical side’ (XAO:0005205) or its children,
  ‘unspecified’ (XAO:0003003)
 'anatomical space' (XAO:0003190) and its children.

**Comment by MardiNenni** [comment]
similar to apoptosis terms in #82

**Comment by matentzn** [comment]
@MardiNenni I would suggest for terms that involve also go terms to take a whitelist approach; each time we implement a “do this for all XAO terms” thing you increase the size of the ontology by many hundred, if not 1000, terms; are you sure you will curate cell proliferation in so many different anatomical entities? I mean, if you are, fair enough, just wondering wether you might want to protect against term proliferation here :)

**Comment by MardiNenni** [comment]
Good point. We have this issue with other requests too. Will hold off on this issue until we can discuss it further amongst ourselves and with @matentzn and @seger on Oct.2

**Comment by MardiNenni** [comment]
After reviewing the current curations,  we would like to move forward with the original request above and add all of the proliferation terms minus the exceptions listed. 

Can we amend any current XPO proliferation terms that do not follow this pattern?
