### ISSUE TITLE
Abnormal Development for all XAO

### ISSUE THREAD

**Issue by MardiNenni** [obophenotype/xenopus-phenotype-ontology#94]
Add abnormal (PATO:0000460) development (GO:0008283) for all XAO terms that aren't:

‘anatomical directions’ (XAO:0003185) or its children,
‘anatomical entity in vitro’ (XAO:0003007) or its children,
‘anatomical side’ (XAO:0005205) or its children,
‘unspecified’ (XAO:0003003)

Following the pattern in #93

**Comment by malcolmfisher103** [comment]
I think the GO term ID here should actually be GO:0032502.

**Comment by matentzn** [comment]
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalDevelopmentOfAnatomicalEntity.yaml

should do.
