### ISSUE TITLE
NTRs for abnormal biological processes

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#95]
We have identified several specific GO terms for which we need 'abnormal' XPO terms for mapping our existing legacy curations. Please see table below of simple PATO-GO combinations. *Some new terms were added 11/1/2019.*

|New Term name|PATO quality|GO term|
|---|---|---|
|abnormal apical constriction involved in gastrulation|PATO:0000460|GO:0003384|
|abnormal axon extension involved in axon guidance|PATO:0000460|GO:0048846|
|abnormal BMP signaling pathway|PATO:0000460|GO:0030509|
|abnormal calcium ion transport|PATO:0000460|GO:0006816|
|abnormal canonical Wnt signaling pathway|PATO:0000460|GO:0060070|
|abnormal cell division|PATO:0000460|GO:0051301|
|abnormal cell migration|PATO:0000460|GO:0016477|
|abnormal chemotaxis|PATO:0000460|GO:0006935|
|abnormal ciliary basal body organization|PATO:0000460|GO:0032053|
|abnormal cilium assembly|PATO:0000460|GO:0060271|
|abnormal cilium disassembly|PATO:0000460|GO:0061523|
|abnormal convergent extension involved in axis elongation|PATO:0000460|GO:0060028|
|abnormal establishment of apical/basal cell polarity|PATO:0000460|GO:0035089|
|abnormal establishment of cell polarity|PATO:0000460|GO:0030010|
|abnormal establishment of epithelial cell planar polarity|PATO:0000460|GO:0090163|
|abnormal establishment of epithelial cell polarity|PATO:0000460|GO:0090162|
|abnormal establishment of tissue polarity|PATO:0000460|GO:0007164|
|abnormal fibroblast growth factor receptor signaling pathway|PATO:0000460|GO:0008543|
|abnormal histone methylation|PATO:0000460|GO:0016571|
|abnormal histone phosphorylation|PATO:0000460|GO:0016572|
|abnormal JNK cascade|PATO:0000460|GO:0007254|
|abnormal activation of meiosis|PATO:0000460|GO:0090427|
|abnormal mitotic spindle assembly|PATO:0000460|GO:0090307|
|abnormal nodal signaling pathway|PATO:0000460|GO:0038092|
|abnormal determination of left/right symmetry|PATO:0000460|GO:0007368|
|abnormal pathway-restricted SMAD protein phosphorylation|PATO:0000460|GO:0060389|
|abnormal protein phosphorylation|PATO:0000460|GO:0006468|
|abnormal phosphorylation of RNA polymerase II C-terminal domain|PATO:0000460|GO:0070816|
|abnormal Wnt signaling pathway, planar cell polarity pathway|PATO:0000460|GO:0060071|
|abnormal protein kinase B signaling|PATO:0000460|GO:0043491|
|abnormal regulation of cell size|PATO:0000460|GO:0008361|
|abnormal regulation of growth rate|PATO:0000460|GO:0040009|
|abnormal regulation of protein folding|PATO:0000460|GO:1903332|
|abnormal retinol dehydrogenase activity|PATO:0000460|GO:0004745|
|abnormal pigment accumulation in tissues|PATO:0000460|GO:0043480|
|abnormal RNA polymerase II activity|PATO:0000460|GO:0001055|
|abnormal sex differentiation|PATO:0000460|GO:0007548|
|abnormal somitogenesis|PATO:0000460|GO:0001756|
|abnormal spermatogonial cell division|PATO:0000460|GO:0007284|
|abnormal spindle assembly|PATO:0000460|GO:0051225|
|abnormal thyroid hormone generation|PATO:0000460|GO:0006590|
|abnormal MAP kinase activity|PATO:0000460|GO:0004707|
|abnormal type B pancreatic cell differentiation|PATO:0000460|GO:0003309|
|abnormal Wnt signaling pathway|PATO:0000460|GO:0016055|
|abnormal wound healing|PATO:0000460|GO:0042060|
|decreased MAP kinase activity|PATO:0002301|GO:0004707|
|delayed embryo development|PATO:0000502|GO:0009790|
|increased alpha-tubulin acetylation|PATO:0002300|GO:0071929|
|decreased alpha-tubulin acetylation|PATO:0002301|GO:0071929|
|increased MAP kinase activity|PATO:0002300|GO:0004707|
|abnormal detection of nodal flow|PATO:0000460|GO:0003127|
|abnormal convergent extension|PATO:0000460|GO:0060026|
|abnormal axon extension involved in regeneration|PATO:0000460|GO:0048677|
|abnormal establishment of planar polarity|PATO:0000460|GO:0001736|
|abnormal apical constriction|PATO:0000460|GO:0003383|
|abnormal axis elongation|PATO:0000460|GO:0003401|
|abnormal neural tube closure|PATO:0000460|GO:0001843|
|abnormal convergent extension involved in neural plate elongation|PATO:0000460|GO:0022007|
|abnormal convergent extension involved in notochord morphogenesis|PATO:0000460|GO:1904126|

There is a slightly more complex term request for some cell migration related terms as well, I'm including this here as GO related, let me know if it should be its own ticket.

|New Term name|PATO quality|GO term|XAO term|
|---|---|---|---|
|abnormal cell migration of multiciliated epidermal cell|PATO:0000460|GO:0016477|XAO:0005179|
|increased cell migration of multiciliated epidermal cell|PATO:0002300|GO:0016477|XAO:0005179|
|decreased cell migration of multiciliated epidermal cell|PATO:0002301|GO:0016477|XAO:0005179|

**Comment by seger** [comment]
The following are molecular functions, so the appropriate molecular function dosdp-patterns will be used.

|New Term name|PATO quality|GO term|
|---|---|---|---|
|abnormal MAP kinase activity|PATO:0000460|GO:0004707|
|decreased MAP kinase activity|PATO:0002301|GO:0004707|
|increased MAP kinase activity|PATO:0002300|GO:0004707|
|abnormal retinol dehydrogenase activity|PATO:0000460|GO:0004745|
|abnormal RNA polymerase II activity|PATO:0000460|GO:0001055|
