### ISSUE TITLE
Fused anatomy XPO terms.

### ISSUE THREAD

**Issue by malcolmfisher103** [obophenotype/xenopus-phenotype-ontology#97]
We had a set of EQE legacy annotations which did not translate well into the XPO. Many of these were based on the fusion of XAO entities, such as in syndactylies or vertebral fusion defects. Ideally cases where the fused XAO terms are of the same type the term name should be of the form 'fused [XAO plural]'

|XPO term|XAO ID<sup>1</sup>|PATO ID|XAO ID<sup>2</sup>|
|---|---|---|---|
|fused eyes|XAO:0005256|PATO:0000642|XAO:0005257|
|hindlimb fused with trunk|XAO:0003031|PATO:0000642|XAO:0003025|
|forelimb fused with trunk|XAO:0003030|PATO:0000642|XAO:0003025|
|fused hindlimb digits|XAO:0003035|PATO:0000642|XAO:0003035|
|fused forelimb digits|XAO:0003036|PATO:0000642|XAO:0003036|
|fused somites|XAO:0000058|PATO:0000642|XAO:0000058|
|fused metatarsals|XAO:0003212|PATO:0000642|XAO:0003212|
|fused tarsi|XAO:0003211|PATO:0000642|XAO:0003211|
|fused carpi|XAO:0003207|PATO:0000642|XAO:0003207|
|anterior branchial crest fused with posterior branchial crest|XAO:0004187|PATO:0000642|XAO:0004188|
|tibia-fibula fused with autopod|XAO:0003213|PATO:0000642|XAO:0004265|
|fused optic stalks|XAO:0000475|PATO:0000642|XAO:0000475|
|fused spikes|XAO:0004489|PATO:0000642|XAO:0004489|
|fused metacarpals|XAO:0003208|PATO:0000642|XAO:0003208|
|fused olfactory epithelia|XAO:0005024|PATO:0000642|XAO:0005024|
|eye fused with brain|XAO:0000179|PATO:0000642|XAO:0000179|
|olfactory pit fused with brain|XAO:0000275|PATO:0000642|XAO:0000179|
|eye fused with olfactory pit|XAO:0000179|PATO:0000642|XAO:0000275|
|eye fused with olfactory epithelium|XAO:0000179|PATO:0000642|XAO:0005024|

Some future consideration may be needed to incorporate specific instances of particular fusions or other limb phenotypes, such as duplications, within regenerating limbs. Could we make equivalents of all XPO terms that incorporate a 'part_of' a limb, either generic or hindlimb/forelimb related to regenerating hindlimb or forelimb, i.e. 'fused metatarsals' would have an equivalent 'fused metatarsals part of regenerating hindlimb'. So for example form the above set we would generate ...

|XPO term|XAO ID<sup>1</sup>|PATO ID|XAO ID<sup>2</sup>|BFO rel|XAO ID<sup>3</sup>|
|---|---|---|---|---|---|
|fused spikes part of regenerating hindlimb|XAO:0004489|PATO:0000642|XAO:0004489|BFO_XB:0000050|XAO:0004107|
|fused spikes part of regenerating forelimb|XAO:0004489|PATO:0000642|XAO:0004489|BFO_XB:0000050|XAO:0004106|
|fused metacarpals part of regenerating forelimb|XAO:0003208|PATO:0000642|XAO:0003208|BFO_XB:0000050|XAO:0004106|
|fused metatarsals part of regenerating hindlimb|XAO:0003212|PATO:0000642|XAO:0003212|BFO_XB:0000050|XAO:0004107|
|fused forelimb digits part of regenerating forelimb|XAO:0003036|PATO:0000642|XAO:0003036|BFO_XB:0000050|XAO:0004106|
|fused hindlimb digits part of regenerating hindlimb|XAO:0003035|PATO:0000642|XAO:0003035|BFO_XB:0000050|XAO:0004107|
|fused tarsi part of regenerating hindlimb|XAO:0003211|PATO:0000642|XAO:0003211|BFO_XB:0000050|XAO:0004107|
|fused carpi part of regenerating forelimb|XAO:0003207|PATO:0000642|XAO:0003207|BFO_XB:0000050|XAO:0004106|
|tibia-fibula fused with autopod part of regenerating hindlimb|XAO:0003213|PATO:0000642|XAO:0004265|BFO_XB:0000050|XAO:0004107|

**Comment by matentzn** [comment]
@seger use http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyFusedAnatomicalEntities.yaml

**Comment by seger** [comment]
@malcolmfisher103 Do you need the terms in the second table (fused structures in regenerating limbs) to finish the mapping to legacy curations, or can they broken out into a separate ticket for later?

**Comment by seger** [comment]
We need a new pattern for fused anatomy in a location.

**Comment by matentzn** [comment]
There you go:

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyFusedAnatomicalEntitiesInLocation.yaml
